version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    dns:  
      - 8.8.8.8  
      - 8.8.4.4 
    ports:
      - '${DEVELOPMENT_BACKEND_PORT}:${DEVELOPMENT_BACKEND_PORT}'
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/backend
      - /frontend/node_modules
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    dns:  
      - 8.8.8.8  
      - 8.8.4.4
    ports:
      - '${DEVELOPMENT_FRONTEND_PORT}:${DEVELOPMENT_FRONTEND_PORT}'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
